services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://DISCORD_TOKEN@DISCORD_ID
    build: .
    extra_hosts:
      - "showman:SHOWMAN_IP"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

  organizr:
    image: organizr/organizr 
    container_name: organizr
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
    volumes:
      - /opt/showman/config/organizr:/config
    ports:
      - 8010:80
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
    volumes:
      - /opt/showman/config/prowlarr:/config
    build: .
    extra_hosts:
      - "showman:SHOWMAN_IP"
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
    volumes:
      - /opt/showman/config/radarr:/config
      - /opt/showman/content:/showman/content
      - /opt/showman/factory:/showman/factory
    ports:
      - 7878:7878
      - 8787:8787
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
    volumes:
      - /opt/showman/config/sonarr:/config
      - /opt/showman/content:/showman/content
      - /opt/showman/factory:/showman/factory
    ports:
      - 8989:8989
      - 9898:9898
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
    volumes:
      - /opt/showman/config/nzbget:/config
      - /opt/showman/factory/:/showman/factory
    build: .
    extra_hosts:
      - "showman:SHOWMAN_IP"
    ports:
      - 6789:6789
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
    volumes:
      - /opt/showman/config/jellyfin:/config
      - /opt/showman/content:/showman/content
    build: .
    extra_hosts:
      - "showman:SHOWMAN_IP"
    ports:
      - 8096:8096
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    build: .
    extra_hosts:
      - "showman:SHOWMAN_IP"
    ports:
      - 5055:5055
    volumes:
      - /opt/showman/config/jellyseerr:/app/config
    restart: unless-stopped

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=SHOWMAN_USER
      - PGID=SHOWMAN_GROUP
      - TZ=America/Chicago
      - URL=SHOWMAN_URL
      - SUBDOMAINS=www,jellyfin,jellyseerr
      - VALIDATION=http
    volumes:
      - /opt/showman/config/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
